"""empty message

Revision ID: 4f8a387d0e0d
Revises: None
Create Date: 2016-01-17 09:15:46.524786

"""

# revision identifiers, used by Alembic.
revision = '4f8a387d0e0d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('slug', sa.String(length=64), nullable=True))
    op.add_column('posts', sa.Column('title', sa.String(length=64), nullable=True))
    op.create_index('ix_posts_published', 'posts', ['published'], unique=False)
    op.create_unique_constraint(None, 'posts', ['slug'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts')
    op.drop_index('ix_posts_published', 'posts')
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'slug')
    op.drop_column('posts', 'published')
    ### end Alembic commands ###
